# Max Gower
# COP 1500
# This program is simply a showcase of what we have learned in COP1500

name = input("Welcome to my program. What is your name? ")
print("Hello", name+"." )
age = input("How old are you? ")
print("You are", age, "years old.")
print("You are about to order fast food. Prepare your body. ")
num_hamburgers = int(input("Enter the number of hamburgers: "))
num_fries = int(input("Enter the number of fries: "))
num_drinks = int(input("Enter the number of drinks: "))
price_hamburger = float(2.00)
price_fries = float(1.50)
price_drinks = float(1.00)
cost_hamburger = (num_hamburgers * price_hamburger)
cost_fries = (num_fries * price_fries)
cost_drinks = (num_drinks * price_drinks)
total_cost = float(cost_hamburger + cost_fries + cost_drinks)
print("Thank you for ordering, your total is: $" + format(total_cost, "0.2f"))
math = input("Are you ready for math? ")
if (math == "yes"):
    print("Good. Now for some numeric operators. ")
else: print("Too bad.")
answer =  6 ** 2 + 3 * 4 // 2
print("6 ** 2 + 3 * 4 // 2 " ,answer)
final = answer%4
print(final)
print("16 + 3 = " ,16 + 3)
print("16 - 3 = " ,16 - 3)
print("16 * 3 = " ,16 * 3)
print("16 ** 3 = " ,16 ** 3)
print("16 / 3 = " ,16 / 3)
print("16 // 3 = " ,16 // 3)
print("16 % 3 = " ,16 % 3)
color = input("What is your favorite color? ")
food = input("What is your favorite food? ")
sport = input("What is your favorite sport? ")
hobby = input("Do you have a hobby, and if so, what is it? ")
car = input("What is your favorite car? ")
job = input("What is your job title? ")
location = input("What place have you always wanted to visit? ")
idol = input("Who is someone you look up to? ")
program = input("Do you think this program ran correctly? ")
print("Your favorite color is:", color)
print("Your favorite food is:", food)
print("Your favorite sport is:", sport)
print("Your hobby is:", hobby)
print("Your favorite car is:", car)
print("Your job title is:", job)
print("A place you want to visit is:", location)
print("A person you idolize is:", idol)
if(program == "yes"):
    print("You think the program ran correctly. Thank you. ")
else:
    print("Thank you for the feedback. I will make sure to correct any mistakes. ")
